theme: jekyll-theme-minimal 
title: Zhou's personal blog.   
logo: /img/pickupmom.jpg
description: Record anything interesting and technical.  

title: Personal basic website with personal typed HTML & CSS   
url: https://zhou-1.github.io/Personal-typed-own-site/  
